### ISSUE TITLE
java.lang.ClassNotFoundException: org.neo4j.kernel.api.proc.Mode

### ISSUE THREAD

**Issue by wenerme** [neo4j-contrib/neo4j-apoc-procedures#230]
```
$ neo4j console
Starting Neo4j.
2016-12-14 07:20:41.006+0000 INFO  Starting...
2016-12-14 07:20:41.445+0000 INFO  Bolt enabled on localhost:7687.
2016-12-14 07:20:42.224+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@32e93662' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@32e93662' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@32e93662' was successfully initialized, but failed to start. Please see attached cause exception.
       	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
       	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:215)
       	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:90)
       	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:67)
       	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@32e93662' was successfully initialized, but failed to start. Please see attached cause exception.
       	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
       	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
       	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:187)
       	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.CommunityFacadeFactory, /usr/local/Cellar/neo4j/3.0.7/libexec/data/databases/graph.db
       	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:144)
       	at org.neo4j.kernel.impl.factory.CommunityFacadeFactory.newFacade(CommunityFacadeFactory.java:40)
       	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:108)
       	at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:55)
       	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
       	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
       	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'apoc.ApocKernelExtensionFactory$1@23428827' was successfully initialized, but failed to start. Please see attached cause exception.
       	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:444)
       	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
       	at org.neo4j.kernel.extension.KernelExtensions.start(KernelExtensions.java:86)
       	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
       	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
       	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:140)
       	... 10 more
Caused by: java.lang.NoClassDefFoundError: org/neo4j/kernel/api/proc/Mode
       	at apoc.schema.AssertSchemaProcedure.signature(AssertSchemaProcedure.java:152)
       	at org.neo4j.kernel.impl.proc.ProcedureRegistry.register(ProcedureRegistry.java:46)
       	at org.neo4j.kernel.impl.proc.Procedures.register(Procedures.java:69)
       	at apoc.ApocKernelExtensionFactory$1.start(ApocKernelExtensionFactory.java:49)
       	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
       	... 15 more
Caused by: java.lang.ClassNotFoundException: org.neo4j.kernel.api.proc.Mode
       	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
       	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
       	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
       	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
       	... 20 more
```

```
$ brew info neo4j
neo4j: stable 3.0.7
Robust (fully ACID) transactional property graph database
https://neo4j.com/
/usr/local/Cellar/neo4j/3.0.7 (146 files, 70.7M) *
  Built from source on 2016-12-14 at 13:43:58
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/neo4j.rb
==> Requirements
Required: java >= 1.8 ✔
```

__Plugins__

* apoc-3.1.0.3-all
* mysql-connector-java-5.1.40

**Comment by wenerme** [comment]
After upgrade to 3.1 everything is ok now, I thought the latest stable version is 3.0.7 which is current version in brew.
