### ISSUE TITLE
apoc 3.0.8.5 causes Neo4j 3.1.1 and 3.2.0-Beta to not start

### ISSUE THREAD

**Issue by bclairmont** [neo4j-contrib/neo4j-apoc-procedures#266]
I cloned the latest apoc and built it on my mac with no errors. The plugin, when installed, causes the below errors and Neo4j fails to start:

neo4j-community-3.2.0-alpha03$ ./bin/neo4j console
Starting Neo4j.
2017-02-02 03:29:02.586+0000 INFO  No SSL certificate found, generating a self-signed certificate..
2017-02-02 03:29:03.162+0000 INFO  Starting...
2017-02-02 03:29:03.780+0000 INFO  Bolt enabled on localhost:7687.
2017-02-02 03:29:04.820+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7a4cd9cd' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7a4cd9cd' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7a4cd9cd' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:216)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:95)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:69)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7a4cd9cd' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:443)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:208)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /Users/clabe03/Documents/neo4j-community-3.2.0-alpha03/data/databases/graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:205)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:120)
	at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:57)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'apoc.ApocKernelExtensionFactory$1@7fac08ae' was successfully initialized, but failed to start. Please see attached cause exception.
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:443)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.extension.KernelExtensions.start(KernelExtensions.java:86)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:201)
	... 9 more
Caused by: java.lang.NoSuchMethodError: org.neo4j.kernel.configuration.Config.getParams()Ljava/util/Map;
	at apoc.ApocConfiguration.initialize(ApocConfiguration.java:24)
	at apoc.ApocKernelExtensionFactory$1.start(ApocKernelExtensionFactory.java:48)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
	... 14 more
2017-02-02 03:29:04.821+0000 INFO  Neo4j Server shutdown initiated by request

I'm not sure if others are experiencing the same issue.

**Comment by sarmbruster** [comment]
APOC has not yet been migrated to 3.2. Doing this is rather high on the list, so please stay tuned.

**Comment by sarmbruster** [comment]
I've just added a 3.2 branch: https://github.com/neo4j-contrib/neo4j-apoc-procedures/tree/3.2. For now you have to build the jar file your own. A release will happen latest when 3.2 goes GA.

**Comment by bclairmont** [comment]
It didn't work in 3.1.1 either... is there a way to use a flag for debugging to find which plugin is causing the issue?

**Comment by jexp** [comment]
Please read the instructions in the readme, use the appropriate version
3.1.0.3 not the version for Neo4j 3.0.x
