### ISSUE TITLE
apoc.util.md5 no longer works in apoc 3.1.2.5

### ISSUE THREAD

**Issue by dimachait** [neo4j-contrib/neo4j-apoc-procedures#356]
There is an error with apoc.util.md5 in apoc 3.1.2.5:

return apoc.util.md5(['a','b'])
Failed to invoke function `apoc.util.md5`: Caused by: java.lang.NoClassDefFoundError: org/apache/commons/codec/digest/DigestUtils

This is an example output that used to work in apoc 3.1.0.3
return apoc.util.md5(['a','b'])

apoc.util.md5(['a','b'])
187ef4436122d1cc2f40dc2b92f0eba0

**Comment by albertodelazzari** [comment]
@dimachait did you build the jar on your own or you did you download it?
The jar that you can download at this link [3.1.2.5](https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/3.1.2.5) doesn't have all the external dependencies. 

@jexp can you please check the jar? The [latest release](https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/3.1.3.6) is ok.

**Comment by dimachait** [comment]
@albertodelazzari I'm not sure since I didn't add that version to the server, let me try that link and I will update you
